config/routes.rb
Rails.application.routes.draw do
  devise_for :users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_scope :user do
    post '/users/sign_in', to: 'devise_sessions#create'
    get '/users/sign_in', to: 'devise_sessions#new'
    delete '/users/sign_out', to: 'devise_sessions#destroy'
  end

  resources :orders, only: [:index]
  resources :order_references, only: [:index] do
    collection do
      get :todays
    end
  end

  root to: 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/accessible.rb
module Accessible
  def orders
    case self.role_name
    when 'admin'
      OrderReference.all
    when 'carrier'
      # TBD: We might have another column to represent order assignment to carriers
      OrderReference.none
    when 'shopper'
      OrderReference.where(shopper: self).distinct
    when 'supervisor'
      # TBD
      OrderReference.none
    when 'vendor'
      OrderReference.joins(:order_items).where("order_items.vendor_id = :vendor_id", vendor_id: self.id).distinct
    end
  end
end

app/models/legacy_client.rb
class LegacyClient < ActiveRecord::Base
  establish_connection Settings.legacy_client
  self.abstract_class = true
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  # by default, all products will be ready
  # pending from SHOPPER
  # shipped from CARRIER
  # deleted if order_item not available
	STATES = ['deleted', 'pending', 'ready', 'shipped']

  belongs_to :order_reference
  belongs_to :vendor, class_name: 'User'
end

app/models/order_reference.rb
class OrderReference < ApplicationRecord
  include Accessible

  belongs_to :canceler, class_name: 'User'
  belongs_to :parent_order, class_name: 'OrderReference'
  belongs_to :shopper, class_name: 'User'
  has_many   :order_items

  scope :today, -> { where(delivery_date: Date.today) }

  store :user_details, accessors: [ :first_name, :last_name, :phone ]

  def shipment_address
  	_address = Spree::Address.find(shipment_address_id)
  	_address.full_address
  end
end

app/models/role.rb
class Role < ApplicationRecord
  LIST = ['admin', 'carrier', 'shopper','supervisor', 'vendor']

  class << self
    Role::LIST.each do |role|
      define_method role do
        by_role(role)
      end
    end

    def by_role(role)
      self.find_by(name: role)
    end
  end
end

app/models/spree/address.rb
class Spree::Address < LegacyClient
  self.table_name = 'spree_addresses'

  belongs_to :country, class_name: "Spree::Country"
  belongs_to :state, class_name: "Spree::State"

  def full_address
    _address = [
      address1,
      address2,
      city,
      (state.try(:name) || ''),
      (country.try(:name) || ''),
      zipcode
    ].join(', ')
    if area.present?

    end
    _address
  end
end

app/models/spree/country.rb
class Spree::Country < LegacyClient
  self.table_name = 'spree_countries'
end

app/models/spree/order.rb
class Spree::Order < LegacyClient
  self.table_name = 'spree_orders'

  def self.completed
    where(state: 'complete')
  end
end

app/models/spree/state.rb
class Spree::State < LegacyClient
  self.table_name = 'spree_states'
end

app/models/spree/user.rb
class Spree::User < LegacyClient
  self.table_name = 'spree_users'
end

app/models/user.rb
class User < ApplicationRecord
  include Accessible
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
    :recoverable, :rememberable, :trackable, :validatable                                                  

  belongs_to :role

  delegate :name, to: :role, prefix: true

  Role::LIST.each do |role|
    define_method "#{role}?" do
      self.role_name == role
    end
  end

  def name
    "#{first_name} #{last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def authorize_user!
    unless (current_user.admin? || current_user.shopper?)
      flash[:error] = 'You are not authorize to access this page!'
      redirect_to root_path and return
    end
  end
end

app/controllers/devise_sessions_controller.rb
class DeviseSessionsController < Devise::SessionsController
  def create
    super do |resource|
      respond_to do |format|
        format.html {
          respond_with resource, location: after_sign_in_path_for(resource) and return
        }
      end
    end
  end

  protected
    def after_sign_in_path_for(resource)
      orders_path
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout 'authentication'

  def index
    if user_signed_in?
      redirect_to todays_order_references_path
    else
      redirect_to users_sign_in_path
    end
  end
end

app/controllers/order_references_controller.rb
class OrderReferencesController < ApplicationController
  layout 'deliverables'

  before_action :authenticate_user!

  def todays
    @orders = current_user.orders.today
  end

  def index
    @orders = current_user.orders
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  layout 'deliverables'

  before_action :authenticate_user!
  before_action :authorize_user!

  def index
  	@orders = Spree::Order.completed
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def create
    # custom sign-in code
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_navigation(current, intended)
    current == intended ? 'active' : ''
  end
end

app/views/common/_header.html.erb
<% current_page = "#{params[:controller]}-#{params[:action]}" %>

<div class='top-header'>
  <div class='header-left'>
    <%= link_to image_tag('grabmuch_logo.png'), '//www.grabmuch.com', class: 'app-logo', target: '_blank' %>
    <%= link_to 'Today\'s Orders', todays_order_references_path, class: "navigation #{current_navigation(current_page, 'order_references-todays')}" %>
    <% if current_user.admin? || current_user.shopper? %>
      <%= link_to 'All Orders', orders_path, class: "navigation #{current_navigation(current_page, 'orders-index')}" %>
    <% end %>
    <%= link_to 'Order References', order_references_path, class: "navigation #{current_navigation(current_page, 'order_references-index')}" %>
  </div>
  <div class='header-right'>
    <div class='user-details navigation'>
      <span ><%= current_user.name %></span>
      <span class='fade'><%= '(' + current_user.email + ')' %></span>
    </div>
    <%= link_to 'Logout', users_sign_out_path, class: 'navigation', method: :delete %>
  </div>
</div>

app/views/devise_sessions/new.html.erb
<%= render template: 'home/index' %>

app/views/home/index.html.erb
<section class="wrapper">
  <div class='logo'>
    <%= image_tag 'grabmuch_logo.png' %>
  </div>
  <div class="modal">
    <div class="modal-window">
      <%= simple_form_for User.new, url: users_sign_in_path do |f| %>
        <div class="modal-inner">
          <label class='authenticated-field'>
            <%= image_tag 'email.png' %>
            <%= f.email_field :email, placeholder: ' john.doe@example.com' %>
          </label>
          <label class='authenticated-field'>
            <%= image_tag 'password.png' %>
            <%= f.password_field :password, placeholder: '********' %>
          </label>
          <%= f.button :submit, 'Log in', class: 'sign-in' %>
        </div>
      <% end %>
    </div>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Deliverables</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/authentication.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Deliverables</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'authentication', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'authentication', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/deliverables.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Deliverables</title>
    <%= csrf_meta_tags %>

    <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
    <%= stylesheet_link_tag    'deliverables', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'deliverables', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'common/header' %>
    <%= yield %>
  </body>
</html>

app/views/order_references/_order.html.erb
<div class='separator'>
  <div class='order-tuple'><%= order.number %></div>
  <div class='order-tuple'><%= order.total %></div>
  <div class='order-tuple'><%= LIST_OF_SLOTS_ADMIN.to_h.key(order.delivery_slot) %></div>
  <div class='order-tuple'><%= order.shipment_address %></div>
  <div class='order-tuple'><%= order.state %></div>
  <div class='order-tuple'><%= order.user_email %></div>
</div>

app/views/order_references/index.html.erb
<div class='all-orders'>
  <div class='orders-headers'>
    <div class='order-header'>Number</div>
    <div class='order-header'>Total</div>
    <div class='order-header'>Delivery Slot</div>
    <div class='order-header'>Shipment Address</div>
    <div class='order-header'>State</div>
    <div class='order-header'>User Email</div>
  </div>
  <div class='orders-tuples'>
    <% if @orders.empty? %>
      <div class='empty-state'>
        No orders assigned to you!!!
      </div>
    <% else %>
      <% @orders.each do |order| %>
        <%= render 'order', order: order %>
      <% end %>
    <% end %>
  </div>
  </div>
</div>

app/views/order_references/todays.html.erb
<div class='all-orders'>
  <div class='orders-headers'>
    <div class='order-header'>Number</div>
    <div class='order-header'>Total</div>
    <div class='order-header'>Delivery Slot</div>
    <div class='order-header'>Shipment Address</div>
    <div class='order-header'>State</div>
    <div class='order-header'>User Email</div>
  </div>
  <div class='orders-tuples'>
    <% if @orders.empty? %>
      <div class='empty-state'>
        You have orders left!
      </div>
    <% else %>
      <% @orders.each do |order| %>
        <%= render 'order', order: order %>
      <% end %>
    <% end %>
  </div>
  </div>
</div>

app/views/orders/_order.html.erb
<div class='separator'>
  <div class='order-tuple'><%= order.number %></div>
  <div class='order-tuple'><%= order.item_total %></div>
  <div class='order-tuple'><%= order.state %></div>
  <div class='order-tuple'><%= order.email %></div>
  <div class='order-tuple'><%= order.delivery_date %></div>
  <div class='order-tuple'><%= LIST_OF_SLOTS_ADMIN.to_h.key(order.delivery_slot) %></div>
</div>

app/views/orders/index.html.erb
<div class='all-orders'>
  <div class='orders-headers'>
    <div class='order-header'>Number</div>
    <div class='order-header'>Item Total</div>
    <div class='order-header'>State</div>
    <div class='order-header'>Email</div>
    <div class='order-header'>Delivery Date</div>
    <div class='order-header'>Delivery Slot</div>
  </div>
  <div class='orders-tuples'>
    <% @orders.each do |order| %>
      <%= render 'orders/order', order: order %>
    <% end %>
  </div>
  </div>
</div>

app/views/users/index.html.erb
<%= simple_form_for(User.new, url: add_delivery_boy_users_path) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :email, required: true, autofocus: true %>
    <%= f.input :password, required: true, hint: ("#{@minimum_password_length} characters minimum" if @minimum_password_length) %>
    <%= f.input :password_confirmation, required: true %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Add delivery boy" %>
  </div>
<% end %>

<% @users.each do |user| %>
  <%= user.email %>
  <%= link_to 'Delete', user_path(user), method: :delete %>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%#= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>